import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from './components/NavBar';
import Header from './components/Header';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='flex h-screen flex-col justify-around p-3 font-pixelify  '>
        <Header />
        <main className='flex flex-col flex-auto flex-wrap'>
          <h1 className='text-8xl font-retro'>Retro Board</h1>

          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
